#!/bin/python3

import math
import os
import random
import re
import sys
from math import sqrt
from math import ceil

# Complete the encryption function below.
def encryption(s):
    sq = sqrt(len(s))
    split_string=[]
    rows = int(sq//1)
    colmn = ceil(sq)
    res = [None]*colmn
    for index in range(0,len(s),colmn):
        split_string.append(s[index:index+colmn])
    for el in split_string:
        for ind in range(len(el)):
            res[ind]=str(res[ind])+str(el[ind])
    
    
    result=[]
    project=" "
    for index in range(len(res)):
        result.append(res[index].replace("None",""))
    
    project = project.join(result)
    return(project)
    
    


    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = encryption(s)

    fptr.write(result + '\n')

    fptr.close()
